import '../models/book.dart';

List<Book> getAdditionalBooks() {
  return [
    // Additional books - expanding the collection
    Book(
      id: '21',
      title: 'Dune',
      author: 'Frank Herbert',
      description: 'A science fiction epic set on the desert planet Arrakis, featuring political intrigue and mystical powers.',
      price: 17.99,
      imageUrl: 'https://picsum.photos/300/400?random=21',
      category: 'Science Fiction',
      stock: 40,
      rating: 4.7,
      reviewCount: 300,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    Book(
      id: '22',
      title: 'The Hobbit',
      author: 'J.R.R. Tolkien',
      description: 'A fantasy adventure about Bilbo Baggins and his unexpected journey with dwarves to reclaim treasure.',
      price: 14.99,
      imageUrl: 'https://picsum.photos/300/400?random=22',
      category: 'Fantasy',
      stock: 55,
      rating: 4.8,
      reviewCount: 450,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    Book(
      id: '23',
      title: 'The Chronicles of Narnia',
      author: 'C.S. Lewis',
      description: 'A magical series about children discovering the world of Narnia through a wardrobe.',
      price: 19.99,
      imageUrl: 'https://picsum.photos/300/400?random=23',
      category: 'Fantasy',
      stock: 35,
      rating: 4.6,
      reviewCount: 280,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    Book(
      id: '24',
      title: 'Gone Girl',
      author: 'Gillian Flynn',
      description: 'A psychological thriller about a missing woman and the dark secrets of her marriage.',
      price: 15.99,
      imageUrl: 'https://picsum.photos/300/400?random=24',
      category: 'Thriller',
      stock: 45,
      rating: 4.3,
      reviewCount: 320,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    Book(
      id: '25',
      title: 'The Night Circus',
      author: 'Erin Morgenstern',
      description: 'A magical tale of two young illusionists competing in a mysterious night circus.',
      price: 16.99,
      imageUrl: 'https://picsum.photos/300/400?random=25',
      category: 'Fantasy',
      stock: 30,
      rating: 4.5,
      reviewCount: 190,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    Book(
      id: '26',
      title: 'Sapiens: A Brief History of Humankind',
      author: 'Yuval Noah Harari',
      description: 'A fascinating exploration of how Homo sapiens conquered the world.',
      price: 18.99,
      imageUrl: 'https://picsum.photos/300/400?random=26',
      category: 'History',
      stock: 40,
      rating: 4.7,
      reviewCount: 400,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    Book(
      id: '27',
      title: 'The Four Winds',
      author: 'Kristin Hannah',
      description: 'A powerful story of love, hope, and resilience during the Great Depression.',
      price: 17.99,
      imageUrl: 'https://picsum.photos/300/400?random=27',
      category: 'Historical Fiction',
      stock: 35,
      rating: 4.6,
      reviewCount: 220,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    Book(
      id: '28',
      title: 'Red Rising',
      author: 'Pierce Brown',
      description: 'A science fiction dystopia about a miner who infiltrates the elite ruling class.',
      price: 15.99,
      imageUrl: 'https://picsum.photos/300/400?random=28',
      category: 'Science Fiction',
      stock: 50,
      rating: 4.4,
      reviewCount: 180,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    Book(
      id: '29',
      title: 'The Thursday Murder Club',
      author: 'Richard Osman',
      description: 'A cozy mystery about four unlikely friends who solve cold cases in their retirement village.',
      price: 16.99,
      imageUrl: 'https://picsum.photos/300/400?random=29',
      category: 'Mystery',
      stock: 45,
      rating: 4.5,
      reviewCount: 250,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    Book(
      id: '30',
      title: 'The Invisible Life of Addie LaRue',
      author: 'V.E. Schwab',
      description: 'A fantasy novel about a young woman cursed to be forgotten by everyone she meets.',
      price: 17.99,
      imageUrl: 'https://picsum.photos/300/400?random=30',
      category: 'Fantasy',
      stock: 40,
      rating: 4.6,
      reviewCount: 300,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    Book(
      id: '31',
      title: 'Think and Grow Rich',
      author: 'Napoleon Hill',
      description: 'A classic self-help book on achieving success and wealth through positive thinking.',
      price: 12.99,
      imageUrl: 'https://picsum.photos/300/400?random=31',
      category: 'Self-Help',
      stock: 60,
      rating: 4.4,
      reviewCount: 500,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    Book(
      id: '32',
      title: 'The Power of Habit',
      author: 'Charles Duhigg',
      description: 'An exploration of how habits work and how to change them for personal improvement.',
      price: 16.99,
      imageUrl: 'https://picsum.photos/300/400?random=32',
      category: 'Self-Help',
      stock: 55,
      rating: 4.5,
      reviewCount: 280,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    Book(
      id: '33',
      title: 'Steve Jobs',
      author: 'Walter Isaacson',
      description: 'The definitive biography of Apple co-founder Steve Jobs.',
      price: 19.99,
      imageUrl: 'https://picsum.photos/300/400?random=33',
      category: 'Biography',
      stock: 25,
      rating: 4.7,
      reviewCount: 350,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    Book(
      id: '34',
      title: 'Becoming',
      author: 'Michelle Obama',
      description: 'The memoir of former First Lady Michelle Obama.',
      price: 18.99,
      imageUrl: 'https://picsum.photos/300/400?random=34',
      category: 'Biography',
      stock: 40,
      rating: 4.8,
      reviewCount: 600,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    Book(
      id: '35',
      title: 'The Lean Startup',
      author: 'Eric Ries',
      description: 'A guide to building successful startups using lean principles.',
      price: 17.99,
      imageUrl: 'https://picsum.photos/300/400?random=35',
      category: 'Business',
      stock: 45,
      rating: 4.3,
      reviewCount: 200,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    Book(
      id: '36',
      title: 'Zero to One',
      author: 'Peter Thiel',
      description: 'Notes on startups, or how to build the future from PayPal co-founder Peter Thiel.',
      price: 16.99,
      imageUrl: 'https://picsum.photos/300/400?random=36',
      category: 'Business',
      stock: 50,
      rating: 4.4,
      reviewCount: 180,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    Book(
      id: '37',
      title: 'The Wright Brothers',
      author: 'David McCullough',
      description: 'The story of the aviation pioneers who invented the airplane.',
      price: 18.99,
      imageUrl: 'https://picsum.photos/300/400?random=37',
      category: 'Biography',
      stock: 30,
      rating: 4.6,
      reviewCount: 150,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    Book(
      id: '38',
      title: 'A Promised Land',
      author: 'Barack Obama',
      description: 'The presidential memoir of Barack Obama covering his early political career.',
      price: 22.99,
      imageUrl: 'https://picsum.photos/300/400?random=38',
      category: 'Biography',
      stock: 35,
      rating: 4.7,
      reviewCount: 400,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    Book(
      id: '39',
      title: 'The Subtle Art of Not Giving a F*ck',
      author: 'Mark Manson',
      description: 'A counterintuitive approach to living a good life by caring about fewer things.',
      price: 15.99,
      imageUrl: 'https://picsum.photos/300/400?random=39',
      category: 'Self-Help',
      stock: 70,
      rating: 4.2,
      reviewCount: 800,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    Book(
      id: '40',
      title: 'Atomic Habits',
      author: 'James Clear',
      description: 'An easy and proven way to build good habits and break bad ones.',
      price: 16.99,
      imageUrl: 'https://picsum.photos/300/400?random=40',
      category: 'Self-Help',
      stock: 65,
      rating: 4.7,
      reviewCount: 1200,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    Book(
      id: '41',
      title: 'The 7 Habits of Highly Effective People',
      author: 'Stephen R. Covey',
      description: 'Powerful lessons in personal change and principles for living an effective life.',
      price: 17.99,
      imageUrl: 'https://picsum.photos/300/400?random=41',
      category: 'Self-Help',
      stock: 55,
      rating: 4.5,
      reviewCount: 900,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    Book(
      id: '42',
      title: 'Man\'s Search for Meaning',
      author: 'Viktor E. Frankl',
      description: 'A psychologist\'s experiences in Nazi concentration camps and his theory of logotherapy.',
      price: 13.99,
      imageUrl: 'https://picsum.photos/300/400?random=42',
      category: 'Psychology',
      stock: 40,
      rating: 4.8,
      reviewCount: 300,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    Book(
      id: '43',
      title: 'Thinking, Fast and Slow',
      author: 'Daniel Kahneman',
      description: 'A groundbreaking exploration of the two systems that drive the way we think.',
      price: 18.99,
      imageUrl: 'https://picsum.photos/300/400?random=43',
      category: 'Psychology',
      stock: 35,
      rating: 4.6,
      reviewCount: 250,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    Book(
      id: '44',
      title: 'The Body Keeps the Score',
      author: 'Bessel van der Kolk',
      description: 'How trauma affects the body and mind, and innovative treatments for recovery.',
      price: 19.99,
      imageUrl: 'https://picsum.photos/300/400?random=44',
      category: 'Psychology',
      stock: 30,
      rating: 4.7,
      reviewCount: 200,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    Book(
      id: '45',
      title: 'The Road',
      author: 'Cormac McCarthy',
      description: 'A post-apocalyptic tale of a father and son journeying across a devastated America.',
      price: 14.99,
      imageUrl: 'https://picsum.photos/300/400?random=45',
      category: 'Fiction',
      stock: 25,
      rating: 4.4,
      reviewCount: 180,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    Book(
      id: '46',
      title: 'The Name of the Wind',
      author: 'Patrick Rothfuss',
      description: 'The first book in the Kingkiller Chronicle, a tale of magic, music, and mystery.',
      price: 16.99,
      imageUrl: 'https://picsum.photos/300/400?random=46',
      category: 'Fantasy',
      stock: 40,
      rating: 4.8,
      reviewCount: 350,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    Book(
      id: '47',
      title: 'The Priory of the Orange Tree',
      author: 'Samantha Shannon',
      description: 'An epic fantasy novel featuring dragons, magic, and political intrigue.',
      price: 18.99,
      imageUrl: 'https://picsum.photos/300/400?random=47',
      category: 'Fantasy',
      stock: 35,
      rating: 4.5,
      reviewCount: 220,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    Book(
      id: '48',
      title: 'Circe',
      author: 'Madeline Miller',
      description: 'A reimagining of the story of Circe, the witch from Greek mythology.',
      price: 15.99,
      imageUrl: 'https://picsum.photos/300/400?random=48',
      category: 'Fantasy',
      stock: 45,
      rating: 4.6,
      reviewCount: 280,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    Book(
      id: '49',
      title: 'The Testaments',
      author: 'Margaret Atwood',
      description: 'The sequel to The Handmaid\'s Tale, set fifteen years after the original.',
      price: 17.99,
      imageUrl: 'https://picsum.photos/300/400?random=49',
      category: 'Science Fiction',
      stock: 50,
      rating: 4.3,
      reviewCount: 300,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    Book(
      id: '50',
      title: 'Normal People',
      author: 'Sally Rooney',
      description: 'A contemporary love story about two young people navigating relationships and mental health.',
      price: 14.99,
      imageUrl: 'https://picsum.photos/300/400?random=50',
      category: 'Fiction',
      stock: 60,
      rating: 4.2,
      reviewCount: 400,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
  ];
}
